version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "calendar-trigger"
s3_bucket = "cyruswong-sam-repo"
s3_prefix = "calendar-trigger"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CalendarUrl=https://calendar.google.com/calendar/ical/spe8ehlqjkv8hd7mdjs3d2g80c%40group.calendar.google.com/public/basic.ics"
